#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-google
Version  : 2
Release  : 1
URL      : https://github.com/google/google-maven-parents/archive/google-2.tar.gz
Source0  : https://github.com/google/google-maven-parents/archive/google-2.tar.gz
Source1  : https://repo1.maven.org/maven2/com/google/google/1/google-1.pom
Source2  : https://repo1.maven.org/maven2/com/google/google/5/google-5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-google-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-google package.
Group: Data

%description data
data components for the mvn-google package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/google/1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/google/google/1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/google/5
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/google/google/5


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/google/google/1/google-1.pom
/usr/share/java/.m2/repository/com/google/google/5/google-5.pom
